fixtures:
  repositories:
    concat:     "git://github.com/puppetlabs/puppetlabs-concat"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql"
    stdlib:     "git://github.com/puppetlabs/puppetlabs-stdlib"

  symlinks:
    gerrit: "#{source_dir}"
