fixtures:
  repositories:
    concat:     "git://github.com/puppetlabs/puppetlabs-concat"
    inifile:    "git://github.com/puppetlabs/puppetlabs-inifile"
    postgresql: 'git://github.com/puppetlabs/puppetlabs-postgresql.git'
    stdlib:     "git://github.com/puppetlabs/puppetlabs-stdlib"

  symlinks:
    gerrit: "#{source_dir}"
